name: Testing script

on:
  push:
    branches: [ main, "*.*.*" ]
  pull_request:
    branches: [ main, "*.*.*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Script
      run: |
        test="this !is! a real sample"
        test1=$(echo $test | grep -Eo "![^!]*!")
